### ISSUE TITLE
Wrong Network Config

### ISSUE THREAD

**Issue by heffneil** [gysmo38/mitsubishi2MQTT#127]
Forgive my ignorance but I must have mistyped the SSID when setting up my system.  The unit is unreachable.  Is there a way to get it back to AP mode or to update the module's settings? Thanks!

Neil

**Comment by lesleypersyn** [comment]
Fallback to AP mode should work. Search wifi...

**Comment by heffneil** [comment]
Super weird.  I unplugged my AP for that network and I could find it.  I reprogrammed it and for whatever reason, I still can't see it getting an IP from DHCP.  I see the unit rebooting (I think) the blue light blinks after some period of time?

**Comment by heffneil** [comment]
Maybe my router just stinks at showing DHCP clients - because now I found it.  Sorry for the trouble- thanks!

**Comment by melyux** [comment]
Hey @heffneil, in that case make sure to close this issue (only if it's working now!).
