### ISSUE TITLE
Errors in logs & not updating

### ISSUE THREAD

**Issue by mattkerrison** [gysmo38/mitsubishi2MQTT#128]
Commands work from Home assistant, however they don't always take, as in Ill change from Auto to fan 4 and it'll kick back to auto until I try a couple times. Also if the Aircon is turned on or off via the remote the state isn't updated in the climate card. I did see this error a number of times in the logs though:

Exception in handle_action_received when handling msg on 'mitsubishi2mqtt/ac-livingroom-rear/state': '{"roomTemperature":24,"temperature":23,"fan":"AUTO","vane":"SWING","wideVane":"SWING","mode":null,"action":null,"compressorFrequency":0}' Traceback (most recent call last): File "/usr/src/homeassistant/homeassistant/components/mqtt/debug_info.py", line 35, in wrapper msg_callback(msg) File "/usr/src/homeassistant/homeassistant/components/mqtt/climate.py", line 399, in handle_action_received payload = render_template(msg, CONF_ACTION_TEMPLATE) File "/usr/src/homeassistant/homeassistant/components/mqtt/climate.py", line 393, in render_template return template(msg.payload) File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 511, in async_render_with_possible_json_value return self._compiled.render(variables).strip() File "/usr/local/lib/python3.8/site-packages/jinja2/environment.py", line 1090, in render self.environment.handle_exception() File "/usr/local/lib/python3.8/site-packages/jinja2/environment.py", line 832, in handle_exception reraise(*rewrite_traceback_stack(source=source)) File "/usr/local/lib/python3.8/site-packages/jinja2/_compat.py", line 28, in reraise raise value.with_traceback(tb) File "<template>", line 1, in top-level template code TypeError: object of type 'NoneType' has no len()

**Comment by gysmo38** [comment]
Old issue. Try new version and open a new one if the issue is still there.
