### ISSUE TITLE
Updating via the web console

### ISSUE THREAD

**Issue by mattkerrison** [gysmo38/mitsubishi2MQTT#136]
I want to update the version running on my ESP8266's without pulling them out, am I right in thinking all I need to do is compile the latest code and then upload the complied code via the web console to update?

**Comment by produdegr** [comment]
Once your ESP8266 is on line it should appear under Main Menu -> Tools -> Port in your Arduino IDE.
Select the required device, then press upload. The sketch will be compiled and uploaded to your ESP8266 via OTA.
However if your mitsubishi2MQTT version is older and does not have OTA then I am afraid you must pull them out.

**Comment by gysmo38** [comment]
Old issue. Try new version and open a new one if the issue is still there.
