### ISSUE TITLE
HA not updating when state changes

### ISSUE THREAD

**Issue by mattkerrison** [gysmo38/mitsubishi2MQTT#137]
Currently I have the old version that doesn't include:

// RSC allow remote and iSensor to update settings
hp.enableExternalUpdate();

However If I make a change with the remote, the aircon sticks to that command just fine, however inside HA the new state isn't reflected, ie I can turn off the Aircon with the IR remote and it will turn off but the card in HA shows as on still (even after 12 hours).

Will changing the _enableExternalUpdate_ resolve this, or is it something else?

**Comment by gysmo38** [comment]
Old issue. Try new version and open a new one if the issue is still there.
