### ISSUE TITLE
Ghost turning on at 20 degree at random times - I'm desperate

### ISSUE THREAD

**Issue by produdegr** [gysmo38/mitsubishi2MQTT#138]
I'm really struggling with this problem and it drives me crazy.
I've installed the F/W on 2 D1 clones without problems and attched them to 2 devices: mitsubishi AP35 and FH35 (europe).
Both devices work perfectly, all functions work without exception, with the web interface or with MQTT.
The FH device is made 2015 and the AP device is 2019 (bought 2021).

The problem is that the AP device turns itself on at random times and sets itself to COOL, 20 degree without altering other values.
I monitored it for 4 days now and it is happening really at random times, sometimes after 8 hours and sometimes every 10 minutes.
When it turns itself on there is NO command comming from a MQTT client, the topic/mode/set cool is not issued by ANYONE and the topic/settings/[..."mode":"cool" ... "action":"cooling"] changes by itself.
The Web interface is protected with a random password and I'm sure it is not open in a browser somewhere.

Now my question to you fellow tinkers, is it possible that mitsubishi did something dodgy to promote it's own solution?
Or could it be that I got a problem with the serial cable. As mentioned all functionality is there and commands are executed almost instantly.

Any thought or your experiences with similar problems would be apreciated very much.
PS. will make a new cable and change the existing one from scratch to see.

**Comment by lesleypersyn** [comment]
@produdegr Please disconnect the D1 and leave the AC alone for some time. Is it really the module? Is someone playing with a remote somewhere (outside)? :)
Just to exclude this option.
Works fine here with same model range.

**Comment by produdegr** [comment]
@lesleypersyn Yep did that already, it hapens only if it is attached to the CN105 ;(

**Comment by produdegr** [comment]
I'm starting to think that it might be a faulty power cable, that somehow makes the D1 reboot itself.
I will definetly re-do the cable.

**Comment by produdegr** [comment]
Finally solved the problem. The problem was not hardware, but a stuck "retained" /topic/mode/set = cool message.
I knew about retain flag, that it should be off, but somehow when trying to configure mqttthings, the setting was retain = true.
And once this message is in your MQTT broker (I use Mosquitto), the ghost turning on happens and you can play with your retain settings as much as you like. If you don't delete this message specifically from your broker, the ghost on happens.

So before trying setting up your end-point, in my case mqttthings for homebridge, set the "retain" flag specifically to FALSE.

I'm wondering why any software would accept a "Retain" flagged MQTT message for ON or OFF in the first place. Especially Mitsubishi AC units have anyhow a restart feature when there is a power cut. And I would consider ON or OFF messages a instant only, if they are "Retain" flagged they may be old...
