### ISSUE TITLE
Ducted unit model option

### ISSUE THREAD

**Issue by jLynx** [gysmo38/mitsubishi2MQTT#140]
Hi it would be awesome to add another model for "ducted units" as they dont have Vanes or Swing.

I have a PEAD-M50JAA ducted unit, so this would then be perfect!

**Comment by gysmo38** [comment]
@jLynx You want a unit without Vanes and Swing? Does it work well with Vanes and Swing?

**Comment by jLynx** [comment]
My unit does not have Vanes or Swing.

**Comment by Sprinterfreak** [comment]
@jLynx Does Your unit work properly and just ignores the vane settings or does the presence of the vane settings cause some malfunction?

**Comment by jLynx** [comment]
Works perfectly fine with no issies

**Comment by jLynx** [comment]
Works perfectly fine with no issues at all. It's just to clean up the UI

**Comment by prashker** [comment]
Is there a "tell" when unit is ducted or is this more a "user should mark this as ducted" thing? From the perspective of Mitsubishi2MQTT (and probably the upstream library) it seems it believes I have some vane settings - despite being a ducted PVA.

![image](https://user-images.githubusercontent.com/1865169/230916638-97070a4c-717a-433c-ad42-644858dd4562.png)

```
{
  "temperature": 19.5,
  "fan": "AUTO",
  "vane": "5",
  "wideVane": "<<",
  "mode": "heat"
}
```

edit: Changing from HEAT to FAN_ONLY seems to change ` vane:5 to vane:1`
