### ISSUE TITLE
Error Compiling with gcc >= 3.0 

### ISSUE THREAD

**Issue by techmagellc** [gysmo38/mitsubishi2MQTT#145]
When you attempt to compile the code using gcc >= 3.0, it fails on the lines containing =='\0'. It needs to be changed to string.isEmpty().

**Comment by juampe** [comment]
To compile again please use   @2.6.3 pio espressif8266 framework

```
[env:WEMOS_D1_Mini]
platform = espressif8266 @2.6.3
board = d1_mini
framework = arduino
lib_deps = ${common.lib_deps_ext}
monitor_speed = 115200
upload_speed = 460800
```
