### ISSUE TITLE
Feature request: gpio for blocking the heatpump

### ISSUE THREAD

**Issue by Rolf-M** [gysmo38/mitsubishi2MQTT#147]
Hi.
It would be great to have an gpio contact on the esp working as block-contact. If this one is opened, the heatpump should switch off and you should not be able to switch it on again.
The purpose is, that I have pumps to get the condensing water away, and normally the fault contact of the pump is connected via an interface box to the heatpump. But I can't use the interface box as this would also need cn105. So my idea was to use a gpio pin on the esp instead.

**Comment by gysmo38** [comment]
I really don't known how to do this. Sorry.
