### ISSUE TITLE
Units are switching on by their own

### ISSUE THREAD

**Issue by asonkel** [gysmo38/mitsubishi2MQTT#148]
After installing the climate I found out that sometimes the indoor units are switching on by their own. I don‘t know if this issue is caused by the direct wiring of the d1 mini( no external pullups), or if this is caused by mqtt. Cause if the units are switched off by IR remote the mqtt state is „idle“ and not off. This is also strange cause i never heard that a idle state is available.

**Comment by produdegr** [comment]
Read this:

https://github.com/gysmo38/mitsubishi2MQTT/issues/135

**Comment by gysmo38** [comment]
Old issue.
