### ISSUE TITLE
web /control is working but connection to HA publishes to mqtt /debug topic

### ISSUE THREAD

**Issue by tbrasser** [gysmo38/mitsubishi2MQTT#15]
This was really easy to set-up, thanks a lot!

I'm still having a few issues though, I get the entity in Home Assistant, but in MQTT logs I can see that after an initial config and status message, it goes to sending debug msges only:

"failed to publish hp status change"

And also, the current temperature tpl seems to fallback to 26 degrees in home-assistant (as in the arduino sketch is defined), but in the webinterface on the /control page, it does show the correct current temperature.

Is something going wrong with setting up the json mqtt message?

**Comment by gysmo38** [comment]
Yes I notice this also. I will check what happen.

**Comment by gysmo38** [comment]
Can you try with the last commit? I hope it will work as expected.

**Comment by tbrasser** [comment]
I'll try as soon as I have access!

**Comment by endeavour** [comment]
Also seeing this issue (the 26c). Also HA keeps trying to put the heatpump into HEAT mode even when I click on cool?

**Comment by endeavour** [comment]
Seems like you are publishing to the ```ha_state_topic``` in multiple places but only in ```hpStatusChanged``` is roomTemperature set... therefore when the topic is published to from any of the other places it breaks the HA UI

**Comment by endeavour** [comment]
https://github.com/gysmo38/mitsubishi2MQTT/pull/16

**Comment by gysmo38** [comment]
Ok I will fix this

**Comment by tbrasser** [comment]
I have performed an OTA (but was connected via VPN so had to do it from commandline specifying IP Port (and password). It succeeded, now waiting for it to come online (hopefully it didn't overwrite/reset my wifi settings).

Will it automatically come back online or do I need to power-cycle it  (or worst case, reconfigure the network settings)?

Also, thanks a bunch for the fixes these past days!

**Comment by gysmo38** [comment]
If you uploaded only sketch, it should come back online. If you upload all the flash, you will loose your configuration.

**Comment by gysmo38** [comment]
no news I close .
