### ISSUE TITLE
Ethernet connection instead WiFi

### ISSUE THREAD

**Issue by gfreccia** [gysmo38/mitsubishi2MQTT#153]
Hi All,

I want to use Ethernet connection instead WiFi (I've Arduino Mega 2560 + W5100 Ethernet Shield).
Do you have any suggestion about how to modify the code?

Thank you!

**Comment by lesleypersyn** [comment]
ESP8266/ESP32 with wired network (shield)?
I don't think it's possible for Arduino due coding, memory, ...

**Comment by gfreccia** [comment]
Why not?
I mean to run the same code inside Arduino Mega 2560 + W5100 Ethernet Shield and use wired network.
I've MQTT code to manage DHT22 sensors running on it, so I think it can run also the pump code.

**Comment by gysmo38** [comment]
Sorry I user ESP8266 with WIFI.
