### ISSUE TITLE
Anyone tried this solution for Mitsubishi Heavy Industries HVACs?

### ISSUE THREAD

**Issue by DYLaKo** [gysmo38/mitsubishi2MQTT#156]
Currently running a custom made controller in my MHI HVAC with [MI-AC-Ctrl](https://github.com/absalom-muc/MHI-AC-Ctrl), which works fine if MQTT is available, but looking for a solution with an embedded webclient to set the HVAC.

This project has a nice and simple webclient, but I cannot find if it is compatible with the MHI HVACs.

Anyone tried it and knows if this works, or knows another solution for MHI HVACs with a web client?

**Comment by gysmo38** [comment]
Close old topic without activity
