### ISSUE TITLE
Doubts about mitsubishi2MQTT

### ISSUE THREAD

**Issue by capacohom** [gysmo38/mitsubishi2MQTT#162]
Hello
I am trying to install your software for the Mitsubishi heat pump in an ESP32 and does not just work.
I have the following doubts:
- I'm not sure what kind of ESP32 I have and therefore what kind of device I have to configure in my Arduino IDE.
- In normal load, ir appears compilation errors regarding the Unit-Conf parameter not declared in Scope.
- When I try to upload with ERROR selected, it supports the firmware upload and the process ends.
- Then on web you can configure all the data, but the control button does not appear.
- In my ESP there are two pins called RX0 and TX0 and another two calls RX2 and TX2, I have tried to connect them at both and it doesn’t work.
- I have assumed that TX and RX threads should go crossed, that is, TX heat pump connects with ESP RX and RX heat pump with ESP TX.
If you have any idea that can be helpful, I appreciate it. Greetings
![44FC685A-59DC-4345-A414-88F7C2FBC3DA](https://user-images.githubusercontent.com/98279959/152525402-fe5d98e7-379c-4b5f-be65-0c5c0d854b0b.jpeg)
![8A74AAFC-E98C-4B20-A456-BFE936A054F9](https://user-images.githubusercontent.com/98279959/152525419-c37ec042-b987-40f4-86f1-91770e0176f9.jpeg)

**Comment by Zeiberstein** [comment]
I can not confirm your problem.

I used these as quide (especially the second one!)
https://chrdavis.github.io/hacking-a-mitsubishi-heat-pump-Part-1/
https://chrdavis.github.io/hacking-a-mitsubishi-heat-pump-Part-2

I used these components. 
https://www.aliexpress.com/item/4000046641683.html
https://www.aliexpress.com/item/1005003232354177.html (the 'Same direction, 5P') 

With the above i got it working from scratch in a few evenings.
