### ISSUE TITLE
Enable reboot from MQTT

### ISSUE THREAD

**Issue by melyux** [gysmo38/mitsubishi2MQTT#164]
Since we do so much stuff through MQTT, rebooting should also be enabled through MQTT. Right now, you have to do a web request.

**Comment by MaxDucy** [comment]
I second this.

**Comment by mminehanNZ** [comment]
+1 for me too

**Comment by gysmo38** [comment]
Good idea. I had it in my todo list

**Comment by gysmo38** [comment]
Done :)
