### ISSUE TITLE
MQTT "state" should be retained so it can be read by HA/etc. immediately

### ISSUE THREAD

**Issue by melyux** [gysmo38/mitsubishi2MQTT#165]
Since the "availability" topic now shows whether the state is current or not, I think we can make the MQTT state showing the current temperature, operating state, etc. retained so that it can be retrieved and read immediately by Home Assistant or anything else that's parsing the HVAC data. Without this retain right now, for example, Home Assistant throws a bunch of errors on startup until the first recurring state topic is delivered by this program. If we retain, we can also remove the recurring MQTT state publishing and only publish on changes.

Any objections?

**Comment by mamrai1** [comment]
Yes, that will also solve the problem with room temperature not sent in every message.. Not remote temp but the hvac's temp

**Comment by JAAS76** [comment]
+1 for me please, 

Not a fix and won't stop the errors messages in HA but will will stop the "26" error temp in HA.

Setup the HVAC in yaml:

current_temperature_template: >-
  {{ value_json.roomTemperature if (value_json is defined and
  value_json.roomTemperature is defined and value_json.roomTemperature|int >
  1.00) else '26.00' }}

remove the "else '26.00' " from the code.

When I change the temp and the target and room over lap or a state is recieved without a roomTemp the current/room temp in HA is not flipped to 26 until the next mqtt state update.

**Comment by gysmo38** [comment]
Please try last version. I change template for HA. It should fiw the 26 error. Not sure for the rest. Open new issue if there is still an issue.
