### ISSUE TITLE
Working with nodeRed

### ISSUE THREAD

**Issue by gfreccia** [gysmo38/mitsubishi2MQTT#166]
Hi All,

I'm using NodeRed but I've only set temp topic working:
_myname/myname/temp/set_

All the others don't work (e.g. _myname/myname/mode/set_)
Could you help me with the right syntax?
Do I've to use always "string" as I use for temp?

Thank you!

**Comment by Andhuooo** [comment]
Which broker are you using ?

**Comment by gfreccia** [comment]
node.js mqtt broker, inside NodeRed.

**Comment by Andhuooo** [comment]
Try another broker  like hivemq

**Comment by gfreccia** [comment]
I can try, but it works properly with Home Assistant.
Could you please point me to the right topics syntax?

Thank you!

**Comment by gysmo38** [comment]
@gfreccia , you have all available command in the readme
