### ISSUE TITLE
Feature request firmware upload 

### ISSUE THREAD

**Issue by jascdk** [gysmo38/mitsubishi2MQTT#17]
Hi gysmo 

Would it be possible to make a firmware upgrade feature through the interface like on the Tasmota firmware ?

**Comment by gysmo38** [comment]
Good idea. I add it to my todo list

**Comment by dzungpv** [comment]
@jascdk try my fork, version 0.5.0, include web firmware update

**Comment by gysmo38** [comment]
@dzungpv please make a new PR without conflics, I will accept it. I think it is better to use one git source.

**Comment by jascdk** [comment]
@dzungpv nice improvements to the Project 😎 can’t wait to try it out ! Thanks a lot 🤘

**Comment by gysmo38** [comment]
Done
