### ISSUE TITLE
Issues - latency and so on the user interface through HA

### ISSUE THREAD

**Issue by jascdk** [gysmo38/mitsubishi2MQTT#18]
Hi Gysmo.

Well - i just got your code flashed to an esp-01 module with an esp8285 mcu on it. I think i have done it right - the code runs and the webpages show correctly. 

BUT - i see some issues on running through HA. When i set / change settings, there is some kind of long latency and when i turn down the temperature it just bounces back on a much higher temperature . Any thoughts what might cause this?

Best

Jacob

**Comment by gysmo38** [comment]
Yes I knwon about the latency between change on Unit and HA. I am working on it.
For the temperature, it go to 31°C ?

**Comment by jascdk** [comment]
regarding temperature - yes it goes to max 31 degrees:)

**Comment by gysmo38** [comment]
I have commit an update. You should have no more latency on HA interface :)

**Comment by jascdk** [comment]
@gysmo38 thanks for your great work! i am going to upload it now - will get back to you with my experiences;)

**Comment by gysmo38** [comment]
I will close this issue because I think it is resolved in last commits. Open a new one if needed.
