### ISSUE TITLE
Openhab MQTT integration

### ISSUE THREAD

**Issue by Lin4fun** [gysmo38/mitsubishi2MQTT#181]
Hi,

I am trying to intergrate the Aircon into Openhab 3 but the autodiscovery do not fit of course for OH3. Can anybody help out to get the right mqtt topics / setup for Openhab 3?

Thanks!

**Comment by gysmo38** [comment]
I am not using Openhab. It compatible with Homeassistant autodiscovey. There is maybe a plugin to activate in OH3 to understand thoses messages.
I think you should search on OpenHab forum: [https://community.openhab.org/t/solved-openhab-3-unable-to-discover-mqtt-things-with-auto-discovery/114254](https://community.openhab.org/t/solved-openhab-3-unable-to-discover-mqtt-things-with-auto-discovery/114254)
