### ISSUE TITLE
MQTT control like original SwiCago / HeatPump example

### ISSUE THREAD

**Issue by hinkma** [gysmo38/mitsubishi2MQTT#183]
Thanks very good software.
Would it be possible to make such an option / selection that MQTT would behave according to the https://github.com/SwiCago/HeatPump/blob/master/examples/mitsubishi_heatpump_mqtt_esp8266_esp32/mitsubishi_heatpump_mqtt_esp8266_esp32.ino code? 
I and many others have Domoticz integration done with that code and the Domoticz plugin.
https://github.com/Masurov/Domoticz-MitsubishiHpMQTT-Plugin

**Comment by gysmo38** [comment]
The project is already based on this code. I do not really understand what you expect. 
You can control the unit with MQTT.
