### ISSUE TITLE
Latest update doesn't log debug messages

### ISSUE THREAD

**Issue by mayankst** [gysmo38/mitsubishi2MQTT#186]
Hi, latest updated seems to have broken packetRecv debug messages. I don't see any packetRecv messages in mqtt client anymore. Also, now the sent packets are shown in parsed values and not in hex.

{
"roomTemperature": 79,
"temperature": 78,
"fan": "4",
"vane": "AUTO",
"wideVane": "SWING",
"mode": "heat",
"action": "heating",
"compressorFrequency": 0
}

VS

{"packetSent":"fc 42 01 30 10 06 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 77 "}

I see following was commented in latest release.

    // TODO REMOVE to get packet cpature on debug
    /*if (!mqtt_client.publish(ha_debug_topic.c_str(), mqttOutput.c_str())) {
      mqtt_client.publish(ha_debug_topic.c_str(), (char*)("Failed to publish to heatpump/debug topic"));
    }*/

**Comment by gysmo38** [comment]
Thank you for creating new issue ;) I remove comment, it work again.
If I found time, I would like to have to debug topics, one for packet and one for message.
