### ISSUE TITLE
ESP32 OTA update in-place not working

### ISSUE THREAD

**Issue by Sprinterfreak** [gysmo38/mitsubishi2MQTT#193]
If the ESP32 is connected to an HVAC, trying to OTA update a new firmware.bin via WebUI fails somwhere around or after upload stage.

The ESP32 becomes unresponsive and starts to blink its LED periodically as if it is in a boot loop forever. The rhythm looks pretty close to the unit poll interval.
Probably the HVAC connected to Serial0 interrupts the update routine badly.

Luckily after a powercycel everything is back to normal on the previous version.

A non-connected ESP32 updates fine via WebUI.

What did I expect?
In-place update possible while ESP is connected to the HVAC

**Comment by Sprinterfreak** [comment]
Seems that enabled debug mode (Setup/Others/Debug: ON) prevents the update to finish.
Turn off debug mode solved this issue so far.

**Comment by giuseppeg88** [comment]
I'm having the same problem but mine is staying unresponsive.  Is there a way to make the ESP work again without physically unplugging it from the air conditioner? Thanks

**Comment by Sprinterfreak** [comment]
In case of trying to upgrade, they did not came back online for me.
If they just go crazy on their own, they tend to come back on their own but sometimes after hours of blocking the HVAC system.
Mine are now running quiet well now. If they disappear, just for minutes but I think this is just luck.

But still this is not ideal as crashes happen multiple times a day. They seem to recover on their own so far.
