### ISSUE TITLE
Web interface on boot???

### ISSUE THREAD

**Issue by jascdk** [gysmo38/mitsubishi2MQTT#2]
Hi.

Are the code made so, you will get some kind of accespoint on boot, so you can insert your credentials?

I have tried flashing it, but it looks like I need to hardcode the wifi credentials in first?

**Comment by gysmo38** [comment]
Hello, First time the module should show wireless network ESP_XXXX. You could connect to web interface to configure your wireless.
To get it work, you need to flash with SPIFFS
I'am currently to work on new version.

**Comment by jascdk** [comment]
Did try it out tonight here again. Doesn't work for me - no accespoint is showing up:( What changes are you going to make? Would it be possible to use the wifimanger library - either by Tzapu or kenn taylor?

**Comment by gysmo38** [comment]
I commit new version. I add autodiscovery for HA with mqtt.
I user this library ESP8266WiFi.h.
I test it again on new module, after burn and restart you should saw HVAC_XXXX SSID. You can connect and go to http://192.168.1.1

**Comment by gysmo38** [comment]
No news. I close this issue. With last version, there is a captival portal.
