### ISSUE TITLE
power_command_topic is deprecated

### ISSUE THREAD

**Issue by freddieleeman** [gysmo38/mitsubishi2MQTT#205]
I noticed this warning in my Home Assistant log today. Unfortunately, I could not find the option in my configuration, but since it triggers five times, and I have five Mitsubishi HVACs running mitsubishi2MQTT, I decided to submit the issue here. I haven't had time to dive into the details yet.

home-assistant.log:
`WARNING (MainThread) [homeassistant.components.mqtt.climate] The 'power_command_topic' option is deprecated, please remove it from your configuration`

**Comment by freddieleeman** [comment]
I couldn't find the `power_command_topic` string which made me second guess if this was related to this repo, but then I found the abbreviation here: https://github.com/gysmo38/mitsubishi2MQTT/blob/f000d6e82cefd80347276dc4edf2d6ea201b3902/src/mitsubishi2mqtt/mitsubishi2mqtt.ino#L1546

Here is the PR for the deprecation: https://github.com/home-assistant/home-assistant.io/pull/25575

**Comment by lesleypersyn** [comment]
PR created to fix this #206

**Comment by drako92** [comment]
> PR created to fix this #206

Thanks for the fix, but i necessary have to modify the 3 files and reflash the firmware, or can i directly upgrade the firmware?

**Comment by gysmo38** [comment]
It is merged, just compile last code
