### ISSUE TITLE
Compilation error: html_common.h: No such file or directory

### ISSUE THREAD

**Issue by cfabiano** [gysmo38/mitsubishi2MQTT#218]
Receiving the following when attempting to compile the code with a new installation of Arduino IDE 2.1.0. I cant seem to find any info for installing the library _html_common.h_

```
C:\Users\user\Documents\Arduino\mitsubishi2mqtt\mitsubishi2mqtt.ino:41:10: fatal error: html_common.h: No such file or directory
   41 | #include "html_common.h"  // common code HTML (like header, footer)
      |          ^~~~~~~~~~~~~~~
compilation terminated.

exit status 1

Compilation error: html_common.h: No such file or directory
```

**Comment by floatplane** [comment]
`html_common.h` is [part of the source tree](https://github.com/gysmo38/mitsubishi2MQTT/blob/master/src/mitsubishi2mqtt/html_common.h). did you clone the whole repo or just copy the .ino file?

**Comment by cfabiano** [comment]
I cloned the repo but for whatever reason IDE couldn't find its way back to the source file directory on my machine. I just started fresh and this time it worked without issue. I appreciate the help.
