### ISSUE TITLE
"Discovered MQTT entities with a name that is equal to the device name" (Home Assistant Warning)

### ISSUE THREAD

**Issue by prashker** [gysmo38/mitsubishi2MQTT#231]
According to latest version of Home Assistant: https://developers.home-assistant.io/blog/2023-057-21-change-naming-mqtt-entities/

![image](https://github.com/gysmo38/mitsubishi2MQTT/assets/1865169/316d0a30-a7c5-45f8-9db9-da654b64f1c2)

I haven't been able to dive in this, but it seems to indicate this is a change needed in how mitsubishi2mqtt reports info to Home Assistant?

I can't recall if this is something I caused myself (based off my config in mitsubishi2mqtt) or is code in needing of fixing, hoping could get some clarification for others who may encounter this warning.

Possible lines of relevance:
https://github.com/gysmo38/mitsubishi2MQTT/blob/965b6614aac197907abe17a5cdc51599f575120e/src/mitsubishi2mqtt/mitsubishi2mqtt.ino#L1635-L1643

**Comment by Allram** [comment]
I believe this was fixed in this PR: https://github.com/gysmo38/mitsubishi2MQTT/pull/228

Download a newer binary from GitHub Actions and flash :⁠-⁠)

**Comment by prashker** [comment]
Aha! Perfect. Thanks @Allram - you are correct. Will close this issue.
