### ISSUE TITLE
Wemos d1 mini v2

### ISSUE THREAD

**Issue by poiex** [gysmo38/mitsubishi2MQTT#237]
How this should be connected i cant get my MSZ-FD25VA working status just says disconnected.
does it need some special schematics or does it work with just straight connection between wemos and cn105.
now it its connected to GPIO1(TX) GPIO3(RX) and on the cn105 its crossed and power is coming from cn105 5V line.

**Comment by Sawadee2u** [comment]
This should help.
[`Link`](https://chrdavis.github.io/hacking-a-mitsubishi-heat-pump-Part-2/)

**Comment by poiex** [comment]
Got it working I bought a NodeMCU V2 and it worked right away.
