### ISSUE TITLE
Binaries shouldn't be in repo.

### ISSUE THREAD

**Issue by shampeon** [gysmo38/mitsubishi2MQTT#25]
I removed a stray binary in src, but binaries should be available as releases on github, not within the source repo. Right now there are 0.45 and 0.47.1 Wemos D1 binaries, and this would presumably grow over time to have a random collection of binaries.

If you build from your repo, add the binaries dir to .gitignore so they won't be committed.

**Comment by gysmo38** [comment]
OK, I created binaries because someone ask me for them. I am not using it. I will delete from my repo and try to add in releases.

**Comment by gysmo38** [comment]
Done. Hope not having made a mistake :p
