### ISSUE TITLE
Installation Problems

### ISSUE THREAD

**Issue by mappolo** [gysmo38/mitsubishi2MQTT#3]
Put the recording information in wemos d1, since I get an error when uploading SPPIFFS. Thank you

**Comment by gysmo38** [comment]
Please try in English.

**Comment by mappolo** [comment]
Put the recording information in wemos d1, since I get an error when uploading SPPIFFS. Thank you

**Comment by gysmo38** [comment]
You do not need to upload file into SPPIFFS. The initial portal will create file for you.
