### ISSUE TITLE
Not sure what i am going incorrect but i am sure its me. Please Help

### ISSUE THREAD

**Issue by mdoary** [gysmo38/mitsubishi2MQTT#30]
@gysmo38
exit status 1
'class HeatPump' has no member named 'isConnected'

**Comment by madzur** [comment]
I had the same issue. Make sure you have the latest [SwiCago](https://github.com/SwiCago/HeatPump) library in your documents/arduino/libraries folder.

**Comment by mdoary** [comment]
Thanks
