### ISSUE TITLE
Control interface disappears after loading

### ISSUE THREAD

**Issue by shampeon** [gysmo38/mitsubishi2MQTT#32]
After flashing and setup the control interface will stop loading. The web console shows an error in the response, and no HTML is in the source.

I think we might be hitting the upper size limit of String sent as a response. https://github.com/esp8266/Arduino/issues/3205

**Comment by jascdk** [comment]
I have the same problem - the control interface is gone :/

**Comment by Shadowpheonix** [comment]
I too am experiencing this issue.

**Comment by chrdavis** [comment]
Same

**Comment by shampeon** [comment]
I'm almost certain it's a problem with the size of the response we're sending, or the String buffer we're using. If you remove the form elements below Fan from html_page_control, the control panel appears. I removed everything and began adding back in form elements one by one. I can get to VANE_2, but adding the option for VANE_3 breaks the control panel.

**Comment by chrdavis** [comment]
I have a PR out with a fix for this.  I send the header, control page, and footer as separate chunks which works.

**Comment by gysmo38** [comment]
I tested the PR on my 5 unit, it look good. I close the issue.
