### ISSUE TITLE
Failing to get Debug info?

### ISSUE THREAD

**Issue by jascdk** [gysmo38/mitsubishi2MQTT#33]
Hi all. 

Anyone else have trouble getting debug info through MQTT? When I enable it I only get Null:null and no response from heatpump??

**Comment by jascdk** [comment]
And - the heatpump can still be controlled by ha

**Comment by MoLow** [comment]
Fixed by https://github.com/gysmo38/mitsubishi2MQTT/pull/46

**Comment by gysmo38** [comment]
Thank @MoLow. I close this issue :)
