### ISSUE TITLE
Does not open control page

### ISSUE THREAD

**Issue by mappolo** [gysmo38/mitsubishi2MQTT#4]
When I try to enter the control page, I can't find it, and it takes a long time to access the different pages.

**Comment by gysmo38** [comment]
Please try in English

**Comment by mappolo** [comment]
When I try to enter the control page, I can't find it, and it takes a long time to access the different pages.

**Comment by gysmo38** [comment]
It should work with last update

**Comment by endeavour** [comment]
I have 2 controllers, 1 works perfectly fine, but the other one has the same issue as described above.
When I try to access the control page the esp8266 reboots itself and the page never loads. Both have the same hardware (adafruit feather huzzah), so not sure what's going on here.

**Comment by endeavour** [comment]
Turns out that this happens if the connection to the heatpump isn't wired up and/or has a loose connection.
