### ISSUE TITLE
Feature request - Localization

### ISSUE THREAD

**Issue by brusarp** [gysmo38/mitsubishi2MQTT#42]
is it possible to implement localization? (like Tasmota, since the GUI has already been taken as a reference ...). I could help for Italian translation...

Thank you!

**Comment by gysmo38** [comment]
Yes good idea. I will look if it is possible.

**Comment by jascdk** [comment]
And I can help with danish language 😎

**Comment by gysmo38** [comment]
I add localization for the menu. I will add pages after.

**Comment by brusarp** [comment]
Good, I will start to write Italian translate...

**Comment by jascdk** [comment]
I Will try make a Danish translate tonight ;)

**Comment by gysmo38** [comment]
I hope everything could be translated. I close this issue. Open a new one if needed
