### ISSUE TITLE
 Multiple command at once?

### ISSUE THREAD

**Issue by picotouch** [gysmo38/mitsubishi2MQTT#43]
Single command sending works fine for me, for example for fan I send value 1 to topic mitsubishi2mqtt/mitsu/fan/set.
For the temperature I send the value to the topic mitsubishi2mqtt/mitsu/temp/set.

Is it possible to send multiple commands, eg temp=24, fan=1, mode=heat as one command? 
If so, how to do that and on what topic to publish?
 I use Node-RED to control AC.

Thanks!

**Comment by gysmo38** [comment]
Sorry, multiple command feature not existe yet. You need to send multiple MQTT topic to set command.
It could be possible but not yet done.

**Comment by picotouch** [comment]
OK thanks.
It's not crucial, but it would be nice to have that option.
Greeting
