### ISSUE TITLE
Minimum and maximum temperature setting is only in C

### ISSUE THREAD

**Issue by shampeon** [gysmo38/mitsubishi2MQTT#47]
<img width="352" alt="Screen Shot 2020-04-10 at 1 17 52 PM" src="https://user-images.githubusercontent.com/5759834/79020463-bb0a9880-7b2d-11ea-8f5e-313ec31b467b.png">

In the Advanced settings, setting the unit to Fahrenheit doesn't affect the minimum/maximum settings. For example, if I set the unit to Fahrenheit and then set the minimum temperature to 61 degrees, the actual setting is 142 degrees. If I set the maximum temperature to 88 degrees, the actual setting is 190 degrees.

From the HA autodiscovery topic:
```
"min_temp":142,
   "max_temp":190,
```

Changing the unit should change the minimum/maximum temperature display, and the conversion should go both ways.

Internally and in the config files, min_temp and max_temp can remain Celsius values. For display, however, they need to match the unit.

**Comment by gysmo38** [comment]
Resolved by @shampeon :)
