### ISSUE TITLE
Failed to open wifi config file

### ISSUE THREAD

**Issue by mappolo** [gysmo38/mitsubishi2MQTT#5]
When flash to boot to the capacitvo portal shows in terminal impossible to open wifi config file.
When entering IP 192.168.1.1 the first screen appears, but when you try to configure it does not go to the next pages and shows them without any css.

**Comment by gysmo38** [comment]
It should work with last update

**Comment by gysmo38** [comment]
It should work with last update

**Comment by duenorh** [comment]
I still have problem with setting my D1 mini from the browser. Same as mappolo.
