### ISSUE TITLE
Confirmation before reset configuration

### ISSUE THREAD

**Issue by spfmoby** [gysmo38/mitsubishi2MQTT#54]
I know the reset configuration button is red, but a simple click by mistake and all is gone. Maybe adding a very basic javascript command on the button could be useful:
something like a onclick="return confirm('Are you sure?')" or equivalent could prevent this.

What do you think about it?

**Comment by shampeon** [comment]
This is an easy fix, and yeah, we should definitely confirm before resetting. PR coming.

**Comment by gysmo38** [comment]
Fixed thank @shampeon
