### ISSUE TITLE
Use platformio for development

### ISSUE THREAD

**Issue by jmvaz** [gysmo38/mitsubishi2MQTT#63]
In order to avoid the problems with the installation of all dependencies, we should prepare the project for platformio.
Once you try it you will never return to ArduinoIDE :)

**Comment by lesleypersyn** [comment]
In the past i did created the platformio.ini but it's not usable anymore due to many changes i did. (and the current project is further developed)

We should normally create this side by side the arduinoIDE.

**Comment by gysmo38** [comment]
I think it's done :)
