### ISSUE TITLE
Mode icon wrong display

### ISSUE THREAD

**Issue by brusarp** [gysmo38/mitsubishi2MQTT#65]
The icon inside the mode combobox is cut on bottom.
I suggest to put
 
block-size: 40px

under the "select" definition inside html_common.h

![Annotazione 2020-05-06 220138](https://user-images.githubusercontent.com/14950532/81222826-3a807000-8fe5-11ea-8abe-fbc6fba8ba33.jpg)

**Comment by gysmo38** [comment]
Ok thank, I will update it

**Comment by gysmo38** [comment]
Done :)
