### ISSUE TITLE
Failed to arrive or write file wifi_config

### ISSUE THREAD

**Issue by mappolo** [gysmo38/mitsubishi2MQTT#7]
I tried everything and I can't read or write in the json files. The output of my terminal is this:
Starting Mitsubishi2MQTT
Connecting to CRASH

Failed to open wifi config file

**Comment by gysmo38** [comment]
You can not open wifi config file. It will be created and manage by the web interface

**Comment by gysmo38** [comment]
No news and it should be ok :)
