### ISSUE TITLE
heatpump state changes when mqtt broker is restarting or starting

### ISSUE THREAD

**Issue by smartboart** [gysmo38/mitsubishi2MQTT#70]
Hello,
theactual state of the heatpumps changes when i restart or start my mqtt broker. For example the temperatur changes to 10 degrees and the device will be switched on. Even  i have configurated minimum temp to 16...

**Comment by juampe** [comment]
I have 4 splits MSZ-HR25VF (some cooling and some stopped while testing) and I cannot replicate this issue when I stop/restart the mosquitto MQTT. The split keeps the configuration among MQTT lost.

**Comment by smartboart** [comment]
We can close this issue... As soon as I only control the splits with mqtt all is perfect.. The remote controls  I have put away and removed batteries..

**Comment by smartboart** [comment]
OK for me
