### ISSUE TITLE
Configuration portal failure and control page.

### ISSUE THREAD

**Issue by mappolo** [gysmo38/mitsubishi2MQTT#8]
When you enter the configuration portal, the first page goes well, but when you go to configure wifi or mqtt you lose the css and do not let enter data.
I have only managed to make it work by configuring a Wi-Fi code, but it still gives me problems.
I tried all this with the last modification several hours ago

**Comment by gysmo38** [comment]
It should be ok now. Maybe  you need to delete everything on the module and start again.

**Comment by gysmo38** [comment]
No news and it should be ok :)
