### ISSUE TITLE
add an I/O Pin for a door/window contact

### ISSUE THREAD

**Issue by Eisbahn** [gysmo38/mitsubishi2MQTT#83]
What about using one (or two) of the unused Pins as Input pin for a door or window contact (as the AC is quite often build on top of a window or door) and transmit the status change of this contact on change? That would allow e.g. stopping the AC if the door/window is open for more than 5min or similar use cases...
[edit] I'm using your SW on a NodeMCU DevBoard ==> having several I/Os unused [/edit]
[edit] sorry for posting in issues, don't know how to share a feature request... [/edit]

**Comment by Eisbahn** [comment]
switched to ESPeasy, the testing one has a full working implementation in it and gives several benefits:
- update only on changed values and no fixed cyclic spamming from aircon
- easy to have a door contact, status LED, presence/radar sensor, humidity device... added
- OTA feature
- big dev group with frequnet updates
No need for me to further develop here anything, could be closed.

**Comment by gysmo38** [comment]
Happy you find a solution for your need :)
