### ISSUE TITLE
deactivation of HomeAssistant does not work from Web-Menue

### ISSUE THREAD

**Issue by Eisbahn** [gysmo38/mitsubishi2MQTT#84]
I'll try to deactivate the HomeAssistant feature (as it is useless for me) via WebMenue by setting it to "OFF" and afterwards clicking on Save & Reboot. After 10sec and the reconnect, HA is still "ON" in the web and also if I sniff the messages it is still active

**Comment by Eisbahn** [comment]
just had a quick look into the code:
as others_haa is by default set to true, the "off" case should be handled from my opinion around line 468...470
`  if (strcmp(haa.c_str(), "ON") == 0) {
    others_haa = true;
  }
`
to somthing like
`  
  if (strcmp(haa.c_str(), "ON") == 0) {
    others_haa = true;
  }
else {
others_haa = false;
`

**Comment by gysmo38** [comment]
Done thank you :)
