### ISSUE TITLE
Best way to get status through http?

### ISSUE THREAD

**Issue by spfmoby** [gysmo38/mitsubishi2MQTT#85]
Hi

I would like to interface a php application with mitsubishi2MQTT. I need to query the PAC to know its states (power, temp, ...) I can parse whatever I get back (json, ...)

What is the best way to achieve this ? I'm not very used to MQTT and I don't know if there is a way to call an URL through http and receive something back.
I'm trying to parse the /control page but it is quite painful and not very clever.
More ideas?

**Comment by gysmo38** [comment]
I think the best way is to use mqtt message.
You should find mqtt lib for PHP.
