### ISSUE TITLE
When in cool mode, the "action" (HVAC state) property is always "cooling" even when unit is idle

### ISSUE THREAD

**Issue by melyux** [gysmo38/mitsubishi2MQTT#95]
Setting the unit to the cool mode puts it into a permanent "cooling" stage instead of alternating between "cooling" and "idle", even when the compressor is actually idle. Is this how it's meant to be?

I saw in the code the line ``//rootInfo["operating"]       = currentStatus.operating;`` was commented out with [this commit](https://github.com/gysmo38/mitsubishi2MQTT/commit/79179b014b5e8e099ac1c1cba833297f714b6d79). Was this for any particular reason? Right now, the `action` property is just a duplicate of the `mode` property according to the code.

**Comment by melyux** [comment]
I saw in the code the line ``//rootInfo["operating"]       = currentStatus.operating;`` was commented out. Was this for any particular reason?

**Comment by dzungpv** [comment]
You are right, you bring back this feature from this commit: https://github.com/gysmo38/mitsubishi2MQTT/commit/9d375f5a7a465d23dd232ae884726f4a39a31f48
